from models import db
from datetime import datetime

class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    employee_code = db.Column(db.String(40), unique=True, nullable=False, index=True)
    name = db.Column(db.String(200), nullable=False)
    department = db.Column(db.String(80), default="HR", index=True)
    designation = db.Column(db.String(120))
    mobile = db.Column(db.String(30))
    photo_url = db.Column(db.String(500))
    joining_date = db.Column(db.Date)
    machine_user_id = db.Column(db.String(60), unique=True, index=True)
    basic_salary = db.Column(db.Float, default=0)
    hra = db.Column(db.Float, default=0)
    other_allowance = db.Column(db.Float, default=0)
    overtime_rate = db.Column(db.Float, default=0)
    active = db.Column(db.Boolean, default=True, index=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class AttendancePunch(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False, index=True)
    punch_time = db.Column(db.DateTime, nullable=False, index=True)
    punch_type = db.Column(db.String(20), default="auto")
    device_ip = db.Column(db.String(60))
    device_event_id = db.Column(db.String(120), unique=True)
    source = db.Column(db.String(20), default="manual")
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    employee = db.relationship("Employee")

class AttendanceDay(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False, index=True)
    work_date = db.Column(db.Date, nullable=False, index=True)
    first_in = db.Column(db.DateTime)
    last_out = db.Column(db.DateTime)
    status = db.Column(db.String(20), default="Absent")
    work_hours = db.Column(db.Float, default=0)
    overtime_hours = db.Column(db.Float, default=0)
    late_minutes = db.Column(db.Integer, default=0)
    remarks = db.Column(db.String(300))
    employee = db.relationship("Employee")
    __table_args__ = (db.UniqueConstraint("employee_id", "work_date", name="uq_attendance_day_employee_date"),)

class SalaryRun(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False, index=True)
    salary_month = db.Column(db.String(7), nullable=False, index=True)
    working_days = db.Column(db.Integer, default=0)
    present_days = db.Column(db.Float, default=0)
    paid_leave_days = db.Column(db.Float, default=0)
    overtime_hours = db.Column(db.Float, default=0)
    basic_earned = db.Column(db.Float, default=0)
    allowances = db.Column(db.Float, default=0)
    overtime_amount = db.Column(db.Float, default=0)
    deductions = db.Column(db.Float, default=0)
    advance = db.Column(db.Float, default=0)
    net_salary = db.Column(db.Float, default=0)
    status = db.Column(db.String(20), default="processed")
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    employee = db.relationship("Employee")
    __table_args__ = (db.UniqueConstraint("employee_id", "salary_month", name="uq_salary_run_employee_month"),)
