'use client';
import {useEffect,useState} from 'react';
import {get,post} from '../lib/api';
export function DealerPaymentPage(){
 const [purchases,setPurchases]=useState([]),[payments,setPayments]=useState([]),[amount,setAmount]=useState(''),[type,setType]=useState('on_account'),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const load=()=>Promise.all([get('/dealer/purchases'),get('/dealer/payments')]).then(([a,b])=>{setPurchases(a.purchases||[]);setPayments(b.payments||[])}).catch(e=>setError(e.message)); useEffect(()=>{load()},[]);
 function toggle(id){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function pay(){setError('');setMsg('');if(Number(amount)<=0){setError('Amount enter karein.');return}if(type!=='on_account'&&!selected.length){setError('Rickshaw select karein.');return}setBusy(true);try{const r=await post('/dealer/payment/create',{amount:Number(amount),allocation_type:type,allocation:selected.map(id=>({challan_id:id}))});if(!window.Cashfree){throw new Error('Cashfree SDK load nahi hua. Page refresh karke try karein.')}const cf=window.Cashfree({mode:r.payment_session_id?.startsWith('session_')?'sandbox':'production'});await cf.checkout({paymentSessionId:r.payment_session_id,redirectTarget:'_modal'});setMsg('Payment window complete hone ke baad status verify ho raha hai…');let n=0;const timer=setInterval(async()=>{n++;try{const s=await get('/dealer/payment/'+r.order_id);if(s.payment?.status==='paid'||n>=10){clearInterval(timer);setMsg(s.payment?.status==='paid'?'Payment successful ✓':'Payment submitted — status pending');load()}}catch{}},2000)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div><script src="https://sdk.cashfree.com/js/v3/cashfree.js"></script><div className="dealerLoanPage"><div className="dealerLoanTop"><div><span className="dealerFormEyebrow">CASHFREE PAYMENT</span><h1>Dealer Online Payment</h1><p>Amount pay karein aur rickshaw ke against, multiple rickshaw ya On Account select karein.</p></div></div>{error&&<div className="error">{error}</div>}{msg&&<div className="card">{msg}</div>}<div className="dealerFormCard"><div className="dealerPersonGrid"><label>Amount *<input className="input" type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Payment Against<select className="input" value={type} onChange={e=>{setType(e.target.value);setSelected([])}}><option value="on_account">On Account</option><option value="single">Single Rickshaw</option><option value="multiple">Multiple Rickshaw</option></select></label></div>{type!=='on_account'&&<div style={{marginTop:16}}><b>Select Rickshaw / Purchase</b>{purchases.map(x=><label key={x.id} style={{display:'flex',gap:10,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #eee'}}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/><span>{x.chassis_no} — {x.product_name} — Challan {x.challan_no}</span></label>)}</div>}<button className="dealerSubmitBtn" disabled={busy} onClick={pay}>{busy?'Opening Cashfree…':'Pay Securely with Cashfree'}</button></div><div className="dealerFormCard"><h2>Payment History</h2><table className="table"><thead><tr><th>Order</th><th>Amount</th><th>Against</th><th>Status</th></tr></thead><tbody>{payments.map(x=><tr key={x.id}><td>{x.order_id}</td><td>₹ {Number(x.amount).toLocaleString('en-IN')}</td><td>{x.allocation_type}</td><td>{x.status}</td></tr>)}</tbody></table></div></div></div>;
}
